<?php
    include "header.phtml"
?>
<div id="container">

    <div id="nav">
        <nav class="navbar navbar-expand-md navbar-light bg-light rounded mb-3">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav text-md-center nav-justified w-100">
                    <li class="nav-item active">
                        <a class="nav-link" href="/home">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/browse">Browse</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/search">Search</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

    <div id="content" class="row">
        <div id="sideBar" class="col-sm-2">
            <form id="filter">
                <h3>Filter:</h3>
                <br>
                <div class="checkbox">
                    <label><input type="checkbox" name="inStockOnly" value="InStockOnly"> In-Stock Only</label>
                </div>
                <br>
                <h6>Show only:</h6>
                <div class="checkbox">
                    <label><input type="checkbox" name="hammers" value="Hammers"> Hammers</label>
                </div>
                <div class="checkbox">
                    <label><input type="checkbox" name="heatGuns" value="Heat Guns"> Heat Guns</label>
                </div>
                <div class="checkbox">
                    <label><input type="checkbox" name="pliers" value="Pliers"> Pliers</label>
                </div>
                <div class="checkbox">
                    <label><input type="checkbox" name="screwdrivers" value="Screwdrivers"> Screwdrivers</label>
                </div>
            </form>
        </div>

        <div id="search" class="col-sm-10">
            <h3>Available Products:</h3>
            <div id="productTable">
            <table id="product" class="table">
                <thead>
                <tr>
                    <th>SKU</th>
                    <th>Name</th>
                    <th>Cost</th>
                    <th>Stock Qty</th>
                </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
            </div>
            <div id="navBtns">
                <button type="submit" id="back" class="btn btn-primary" onclick="return backProducts()">Back</button>
                <button type="submit" id="next" class="btn btn-primary" onclick="return nextProducts()">Next</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    let current;
    window.onload = function() {
        current = 0;
        getTableData();
    };

    function getTableData() {
        let xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState === 4 && this.status === 200) {
//                console.log(this.responseText);
                const data = JSON.parse(this.responseText);
//                console.log(data);
                loadTable(data);
            }
        };
        xhttp.open("POST", "/products", true);
        xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
        xhttp.send("current=" + current);
    }

    function loadTable(data) {
        let table = document.getElementById('product');
        data.forEach(function (product) {
//            console.log(product);
//            console.log(product._sku);
            let row = table.insertRow();

            let sku = row.insertCell(0);
            sku.innerHTML = product._sku;
            let name = row.insertCell(1);
            name.innerHTML = product._name;
            let cost = row.insertCell(2);
            cost.innerHTML = product._cost;
            let qty = row.insertCell(3);
            qty.innerHTML = product._stock;
        })
    }

    function nextProducts() {
        current += 20;
        getTableData();
    }

    function backProducts() {
        if (current !== 0) current -= 20;
        getTableData();
    }
</script>
<?php
    include "footer.phtml"
?>
