<?php
    include "header.phtml"
?>
<div id="container">

    <div id="nav">
        <nav class="navbar navbar-expand-md navbar-light bg-light rounded mb-3">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav text-md-center nav-justified w-100">
                    <li class="nav-item active">
                        <a class="nav-link" href="/welcome">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/browse">Browse</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/search">Search</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

    <div id="content">
        <div id="sideBar">
            <form id="filter">
                <h3>Filter:</h3>
                <input type="checkbox" name="inStockOnly" value="In stock only">

                <h6>Show only:</h6>
                <input type="checkbox" name="hammers" value="Hammers">
                <input type="checkbox" name="heatGuns" value="Heat Guns">
                <input type="checkbox" name="pliers" value="Pliers">
                <input type="checkbox" name="screwdrivers" value="Screwdrivers">

            </form>
        </div>
        <div id="search">
            <h3>Available Products:</h3>
            <table>
                <thead>
                <tr>
                    <th>SKU</th>
                    <th>Name</th>
                    <th>Cost</th>
                    <th>Stock Qty</th>
                </tr>
                </thead>
                <tbody>
                <?php
                    foreach ($items as $item) {
                        echo $item->printRow();
                    }
                ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?php
    include "footer.phtml"
?>
