<?php
    include "header.phtml"
?>
<div id="container">

    <div id="nav">
        <nav class="navbar navbar-expand-md navbar-light bg-light rounded mb-3">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav text-md-center nav-justified w-100">
                    <li class="nav-item active">
                        <a class="nav-link" href="/home">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/browse">Browse</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/search">Search</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

    <div id="content" class="row">
        <div id="sideBar" class="col-sm-2">
            <form id="filter">
                <h3>Filter:</h3>
                <br>
                <div class="checkbox">
                    <label><input type="checkbox" id="inStockOnly" name="inStockOnly" value="InStockOnly" onclick="changeInStockOnly()"> In-Stock Only</label>
                </div>
                <br>
                <h6>Show only:</h6>
                <div class="checkbox">
                    <label><input type="checkbox" id="hammers" name="hammers" value="Hammers" onclick="changeHammers()"> Hammers</label>
                </div>
                <div class="checkbox">
                    <label><input type="checkbox" id="heatGuns" name="heatGuns" value="Heat Guns" onclick="changeHeatGuns()"> Heat Guns</label>
                </div>
                <div class="checkbox">
                    <label><input type="checkbox" id="pliers" name="pliers" value="Pliers" onclick="changePliers()"> Pliers</label>
                </div>
                <div class="checkbox">
                    <label><input type="checkbox" id="screwdrivers" name="screwdrivers" value="Screwdrivers" onclick="changeScrewdrivers()"> Screwdrivers</label>
                </div>
            </form>
        </div>

        <div id="search" class="col-sm-10">
            <h3>Available Products:</h3>
            <div id="productTable">
            <table id="product" class="table">
                <thead>
                <tr>
                    <th>SKU</th>
                    <th>Name</th>
                    <th>Cost</th>
                    <th>Stock Qty</th>
                </tr>
                </thead>
                <tbody id="productBody">

                </tbody>
            </table>
            </div>
            <div id="navBtns">
                <button type="submit" id="back" class="btn btn-primary" onclick="return backProducts()">Back</button>
                <button type="submit" id="next" class="btn btn-primary" onclick="return nextProducts()">Next</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    let filterOptions = {
        inStockOnly : false,
        hammers : false,
        heatGuns : false,
        pliers : false,
        screwdrivers : false,
        getFilters : function() {
            let filters = "";
            if (this.inStockOnly) filters += "&inStockOnly=true";
            if (this.hammers) filters += "&hammers=true";
            if (this.heatGuns) filters += "&heatGuns=true";
            if (this.pliers) filters += "&pliers=true";
            if (this.screwdrivers) filters += "&screwdrivers=true";
            return filters;
        },
        anyFilters : function () {
            if (this.inStockOnly) return true;
            if (this.hammers) return true;
            if (this.heatGuns) return true;
            if (this.pliers) return true;
            if (this.screwdrivers) return true;
            return false;
        }
    };

    let current;
    window.onload = function() {
        current = 0;
        getTableData();
    };

    function getTableData() {
        console.log(filterOptions);

        let xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState === 4 && this.status === 200) {
//                console.log(this.responseText);
                const data = JSON.parse(this.responseText);
//                console.log(data);
                loadTable(data);
            }
        };
        xhttp.open("POST", "/products", true);
        xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
        if (filterOptions.anyFilters()) {
            xhttp.send("current=" + current + filterOptions.getFilters());
        } else {
            xhttp.send("current=" + current);
        }
    }

    function loadTable(data) {
        let table = document.getElementById('product');
        let rowCount = table.rows.length;
        while(--rowCount) { table.deleteRow(rowCount) }

        data.forEach(function (product) {
//            console.log(product);
//            console.log(product._sku);
            let row = table.insertRow();

            let sku = row.insertCell(0);
            sku.innerHTML = product._sku;
            let name = row.insertCell(1);
            name.innerHTML = product._name;
            let cost = row.insertCell(2);
            cost.innerHTML = product._cost;
            let qty = row.insertCell(3);
            qty.innerHTML = product._stock;
        })
    }

    function changeInStockOnly() {
        const inStockOnlyCbx = document.getElementById('inStockOnly');
        filterOptions.inStockOnly = inStockOnlyCbx.checked;
        getTableData();
    }

    function changeHammers() {
        const hammersCbx = document.getElementById('hammers');
        filterOptions.hammers = hammersCbx.checked;
        getTableData();
    }

    function changeHeatGuns() {
        const heatGunsCbx = document.getElementById('heatGuns');
        filterOptions.heatGuns = heatGunsCbx.checked;
        getTableData();
    }

    function changePliers() {
        const pliersCbx = document.getElementById('pliers');
        filterOptions.inStockOnly = pliersCbx.checked;
        getTableData();
    }

    function changeScrewdrivers() {
        const screwdriversCbx = document.getElementById('screwdrivers');
        filterOptions.screwdrivers = screwdriversCbx.checked;
        getTableData();
    }

    function nextProducts() {
        current += 20;
        getTableData();
    }

    function backProducts() {
        if (current !== 0) current -= 20;
        getTableData();
    }
</script>
<?php
    include "footer.phtml"
?>
