<?php
    include "header.phtml"
?>
<div id="container">
    <div id="titleBar">
        <h1>Welcome to Toolshed</h1>
    </div>
    <br>
    <div class="row">
        <div id="logo" class="col-sm-4">
            <img src="/static/images/hammer.png" id="logoImage"/>
        </div>
        <div id="formHolder" class="col-sm-4">
            <form action="/login" method="POST">
                <div class="form-group row">
                    <label for="username" class="col-sm-4 col-form-label">Username: </label>
                    <div class="col-sm-8">
                        <input type="text" name="username" placeholder="Username" id="username" class="form-control" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="password" class="col-sm-4 col-form-label">Password: </label>
                    <div class="col-sm-8">
                        <input type="password" name="password" placeholder="Password" id="password" class="form-control" required>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            <?php
            if ($error) { // if exists
                echo "<p class='alert alert-danger'> $error </p>";
            }
            ?>
            <br>
            <p style="text-align: center;">Don't have an account? <a href="/register">Register</a></p>
        </div>

        <div id="padding" class="col-sm-4">
            <p></p>
        </div>

    </div>
</div>
<?php
    include "footer.phtml"
?>
