<?php
    include "header.phtml"
?>
<div id="container">
    <div id="titleBar">
        <h1>Welcome to Toolshed</h1>
    </div>
    <br>
    <div id="formHolder">
        <form action="/register" method="POST" id="validate">
            <div class="form-group row">
                <label for="name" class="col-sm-4 col-form-label">Name: </label>
                <div class="col-sm-8">
                    <input type="text" name="name" id="name" placeholder="Name" class="form-control" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="username" class="col-sm-4 col-form-label">Username: </label>
                <div class="col-sm-8">
                    <input type="text" name="username" id="username" placeholder="Username" class="form-control" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="email" class="col-sm-4 col-form-label">Email: </label>
                <div class="col-sm-8">
                    <input type="email" name="email" id="email" placeholder="email@example.com" class="form-control" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="password" class="col-sm-4 col-form-label">Password: </label>
                <div class="col-sm-8">
                    <input type="password" name="password" id="password" placeholder="Password" class="form-control" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="repeat" class="col-sm-4 col-form-label">Password: </label>
                <div class="col-sm-8">
                    <input type="password" name="repeat" id="repeat" placeholder="Password" class="form-control" required>
                    <div class="invalid-feedback">
                        <p>Password doesn't match</p>
                    </div>
                </div>
            </div>
            <button type="submit" id="submit" class="btn btn-primary">Submit</button>
        </form>
        <?php
            if ($error) { // if exists
                echo "<p class='alert alert-danger'> $error </p>";
            }
        ?>
    </div>
</div>

<script type="javascript">
    (function() {
        window.addEventListener("load", function() {
            let form = document.getElementById("validate");
            form.addEventListener("submit", function(event) {
                if (form.checkValidity() == false) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                const pw = document.getElementById("password").value;
                const pw2 = document.getElementById("repeat").value;
                if (pw !== pw2) {

                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add("was-validated");
            }, false);
        }, false);
    }());
</script>
<?php
    include "footer.phtml"
?>
