<?php
    include "header.phtml"
?>
<div id="container">
    <div id="titleBar">
        <h1>Welcome to Toolshed</h1>
    </div>
    <br>
    <div id="formHolder">
        <form action="/register" onsubmit="validateForm()" method="POST" name="register">
            <div class="form-group row">
                <label for="name" class="col-sm-4 col-form-label">Name: </label>
                <div class="col-sm-8">
                    <input type="text" name="name" id="name" placeholder="Name" class="form-control" required>
                </div>
            </div>
            <div class="form-group row" id="usernameDiv">
                <label for="username" class="col-sm-4 col-form-label">Username: </label>
                <div class="col-sm-8">
                    <input type="text" name="username" id="username" placeholder="Username" class="form-control"  required>
                </div>
            </div>
            <div class="form-group row">
                <label for="email" class="col-sm-4 col-form-label">Email: </label>
                <div class="col-sm-8">
                    <input type="email" name="email" id="email" placeholder="email@example.com" class="form-control" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="password" class="col-sm-4 col-form-label">Password: </label>
                <div class="col-sm-8">
                    <input type="password" name="password" id="password" placeholder="Password" class="form-control" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="repeat" class="col-sm-4 col-form-label">Password: </label>
                <div class="col-sm-8">
                    <input type="password" name="repeat" id="repeat" placeholder="Password" class="form-control" oninput="checkPasswords()" required>
                    <p id="errorNotification" class='alert alert-danger' style="display: none; position: absolute;"></p>

                </div>

            </div>
            <div class="form-group row">
                <div class="col-sm-offset-6 col-sm-6">
                    <button type="submit" id="submit" class="btn btn-primary" onclick="return validateForm()">Submit</button>
                </div>
            </div>
        </form>
        <div id="demo">
            <br>

        </div>
        <?php
            if ($error) { // if exists
                echo "<p class='alert alert-danger'> $error </p>";
            }
        ?>
    </div>
</div>

<script>

    let username = document.getElementById('username');
    let validUsername = true;
    let usernameError = "";
    let passwordError = "";

    const bSubmit = document.getElementById('submit');

    let errorNotification = document.getElementById('errorNotification');

    username.addEventListener("input", function (event) {
//        console.log(event);
        if (username.value !== "") {
            checkUserName();
            //console.log(username.value)
        }
    });

    function validateForm() {
        const pw1 = document.getElementById("password");
        const pw2 = document.getElementById("repeat");
        if (pw1.value !== pw2.value) {
            //console.log("passwords do not match");
            return false;
        } else {
            //console.log("passwords match!");
            return true;
        }
    }

    function checkPasswords() {
        const pw1 = document.getElementById("password");
        const pw2 = document.getElementById("repeat");
        if (pw1.value !== pw2.value) {
            errorNotification.style.display = "initial";
            passwordError = "Passwords Do Not Match";
            errorNotification.innerHTML = usernameError + passwordError;
            console.log("passwords do not match");
            disableSubmit();
        } else {
            passwordError = "";
            if (usernameError === "") {
                errorNotification.style.display = "none";
            } else {
                errorNotification.innerHTML = usernameError;
            }
            enableSubmit();
        }
    }

    function checkUserName() {
//        console.log(username.value);
        const usernameToCheck = username.value;
        let xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState === 4 && this.status === 200) {
                const data = JSON.parse(this.responseText);
                console.log(data);
                validUsername = data.valid;
                console.log(validUsername);

                if (!validUsername) {
                    usernameError = "Invalid Username<br>";
                    errorNotification.style.display = "initial";
                    errorNotification.innerHTML = usernameError + passwordError;
                    disableSubmit();
                } else {
                    usernameError = "";
                    if (passwordError === "") { errorNotification.style.display = "none" }
                    else { errorNotification.innerHTML = passwordError; }

                    enableSubmit();
                }
            }
        };
        xhttp.open("POST", "/checkUserName", true);
        xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
        xhttp.send("username=" + usernameToCheck);

    }

    function disableSubmit() {
        bSubmit.disabled = true;

    }

    function enableSubmit() {
        if ((usernameError === "") && (passwordError === "")) {
            bSubmit.disabled = false;
        }

    }
</script>
<?php
    include "footer.phtml"
?>
