<?php
    include "header.phtml"
?>
<div id="container">
    <div id="titleBar">
        <h1>Welcome to Toolshed</h1>
    </div>
    <br>
    <div id="formHolder">
        <form action="/register" onsubmit="validateForm()" method="POST" name="register">
            <div class="form-group row">
                <label for="name" class="col-sm-4 col-form-label">Name: </label>
                <div class="col-sm-8">
                    <input type="text" name="name" id="name" placeholder="Name" class="form-control" required>
                </div>
            </div>
            <div class="form-group row" id="usernameDiv">
                <label for="username" class="col-sm-4 col-form-label">Username: </label>
                <div class="col-sm-8">
                    <input type="text" name="username" id="username" placeholder="Username" class="form-control" oninput="usernameCheck()" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="email" class="col-sm-4 col-form-label">Email: </label>
                <div class="col-sm-8">
                    <input type="email" name="email" id="email" placeholder="email@example.com" class="form-control" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="password" class="col-sm-4 col-form-label">Password: </label>
                <div class="col-sm-8">
                    <input type="password" name="password" id="password" placeholder="Password" class="form-control" oninput="passwordLength()" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="repeat" class="col-sm-4 col-form-label">Password: </label>
                <div class="col-sm-8">
                    <input type="password" name="repeat" id="repeat" placeholder="Password" class="form-control" oninput="checkPasswords()" required>
                    <p id="errorNotification" class='alert alert-danger' style="display: none; position: absolute;"></p>

                </div>

            </div>
            <div class="form-group row">
                <div class="col-sm-offset-6 col-sm-6">
                    <button type="submit" id="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
        <div id="demo">
            <br>

        </div>
        <?php
            if ($error) { // if exists
                echo "<p class='alert alert-danger'> $error </p>";
            }
        ?>
    </div>
</div>

<script>

    let username = document.getElementById('username');
    let validUsername = true;
    let usernameError = "";
    let passwordMatchError = "";
    let passwordLengthError = "";

    const bSubmit = document.getElementById('submit');

    let errorNotification = document.getElementById('errorNotification');


    function checkPasswords() {
        const pw1 = document.getElementById("password");
        const pw2 = document.getElementById("repeat");
        if (pw1.value !== pw2.value) {
            passwordMatchError = "Passwords Do Not Match";
            disableSubmit();
        } else {
            passwordMatchError = "";
            enableSubmit();
        }
    }


    function passwordLength() {
        checkPasswords();
        const pw = document.getElementById("password");
        if (pw.value.length < 7 || pw.value.length > 15) {
            passwordLengthError = "Passwords Must Be Between 7 and 15 Characters Long<br>";
            disableSubmit();
            console.log("password error: " + passwordLengthError);
        } else {
            passwordLengthError = "";
            console.log("password error: " + passwordLengthError);
            enableSubmit();
        }
    }

    function usernameCheck() {
        const usernameToCheck = username.value;
        let xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState === 4 && this.status === 200) {
                const data = JSON.parse(this.responseText);
                validUsername = data.valid;

                if (!isAlphaNumeric(usernameToCheck)) {
                    usernameError = "Username Can Only Contain Numbers and Letters<br>";
                    disableSubmit();
                    return
                } else {
                    usernameError = "";
                    enableSubmit();
                }

                if (!validUsername) {
                    usernameError = "Username Already Exists<br>";
                    disableSubmit();
                } else {
                    usernameError = "";
                    enableSubmit();
                }
            }
        };
        xhttp.open("POST", "/checkUserName", true);
        xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
        xhttp.send("username=" + usernameToCheck);

    }

    function disableSubmit() {
        if (passwordLengthError !== "" || passwordMatchError !== "" || usernameError !== "") {
            bSubmit.disabled = true;
            errorNotification.style.display = "initial";
            errorNotification.innerHTML = usernameError + passwordLengthError + passwordMatchError;

        }

    }

    function enableSubmit() {
        if ((usernameError === "") && (passwordMatchError === "") && (passwordLengthError === "")) {
            bSubmit.disabled = false;
            errorNotification.style.display = "none";
        }

    }

    function isAlphaNumeric(str) {
        let code, i, len;
        i = 0;

        for (len = str.length; i < len; i++) {
            code = str.charCodeAt(i);
            if (!(code > 47 && code < 58) && // numeric (0-9)
                !(code > 64 && code < 91) && // upper alpha (A-Z)
                !(code > 96 && code < 123)) { // lower alpha (a-z)
                return false;
            }
        }
        return true;
    }

    function hasUpperCase(str) {
        let code, i, len;
        i = 0;
        for (len = str.length; i < len; i++) {
            code = str.charCodeAt(i);
            if (code > 64 && code < 91) { //(A-z)
                return true;
            }
        }
        return false;
    }

</script>
<?php
    include "footer.phtml"
?>
