<?php

/*Dylan Cross ID#15219491
 *Jordan Felix ID#15152699
 *Assignment 3
 */

include "header.phtml";
    include "nav.phtml";
?>
<div id="container">
    <div id="content" class="col-sm-12">
        <div id="searchBar" class="col-sm-6">
            <div class="form-group row">
                <label for="name" class="col-sm-4 col-form-label">Search: </label>
                <div class="col-sm-8">
                    <input type="text" id="search" placeholder="Search" class="form-control" oninput="return search()">
                    <p id="errorNotification" class='alert alert-danger' style="display: none; position: absolute;">No results found</p>
                </div>
            </div>
        </div>

        <h3>Available Products:</h3>

        <div id="searchTable">
            <table id="product" class="table">
                <thead>
                <tr>
                    <th>SKU</th>
                    <th>Name</th>
                    <th>Cost</th>
                    <th>Stock Qty</th>
                </tr>
                </thead>
                <tbody id="productBody">

                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    const searchBar = document.getElementById("search");

    function search() {
        console.log(searchBar.value);
        let xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState === 4 && this.status === 200) {
//                console.log(this.responseText);
                const data = JSON.parse(this.responseText);
//                console.log(data);
                loadTable(data);
            }
        };
        xhttp.open("POST", "/search", true);
        xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
        xhttp.send("search=" + searchBar.value);
    }

    function loadTable(data) {
        let errorNotification = document.getElementById('errorNotification');
        let table = document.getElementById('product');
        let rowCount = table.rows.length;
        while(--rowCount) { table.deleteRow(rowCount) }

        console.log(data);
        if (data.length === 0) {
            errorNotification.style.display = "initial";
        }

        data.forEach(function (product) {
//            console.log(product);
//            console.log(product._sku);
            errorNotification.style.display = "none";
            let row = table.insertRow();

            let sku = row.insertCell(0);
            sku.innerHTML = product._sku;
            let name = row.insertCell(1);
            name.innerHTML = product._name;
            let cost = row.insertCell(2);
            cost.innerHTML = product._cost;
            let qty = row.insertCell(3);
            qty.innerHTML = product._stock;
        })
    }
</script>
<?php
    include "footer.phtml"
?>
