<?php
    include "header.phtml"
?>
<div id="container">

    <div id="nav">
        <nav class="navbar navbar-expand-md navbar-light bg-light rounded mb-3">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav text-md-center nav-justified w-100">
                    <li class="nav-item active">
                        <a class="nav-link" href="/home">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/browse">Browse</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/search">Search</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

    <div id="content" class="col-sm-12">
        <div id="searchBar" class="col-sm-6">
            <div class="form-group row">
                <label for="name" class="col-sm-4 col-form-label">Search: </label>
                <div class="col-sm-8">
                    <input type="text" id="search" placeholder="Search" class="form-control" oninput="return search()">
                </div>
            </div>
        </div>

        <h3>Available Products:</h3>

        <div id="productTable">
            <table id="product" class="table">
                <thead>
                <tr>
                    <th>SKU</th>
                    <th>Name</th>
                    <th>Cost</th>
                    <th>Stock Qty</th>
                </tr>
                </thead>
                <tbody id="productBody">

                </tbody>
            </table>
        </div>

        <div id="navBtns">
            <button type="submit" id="back" class="btn btn-primary" onclick="return backProducts()">Back</button>
            <button type="submit" id="next" class="btn btn-primary" onclick="return nextProducts()">Next</button>
        </div>
    </div>
</div>

<script type="text/javascript">
    const searchBar = document.getElementById("search");
    function search() {
        console.log(searchBar.value);
    }
</script>
<?php
    include "footer.phtml"
?>
