<?php
    include "header.phtml";
    include "nav.phtml";
?>
<div id="container">

    <div id="content">
        <h3>Welcome <?php if ($accountName) echo $accountName;?></h3>
        <hr>
        <h5>Usage Instructions:</h5>
        <p>
            Browse all products <a href="/browse">here</a>
            <br>
            or
            <br>
            Search for a specific product <a href="/search">here</a>
        </p>
    </div>
</div>
<?php
    include "footer.phtml"
?>
