<?php
    include "header.phtml"
?>
<div id="container">

    <div id="nav">
        <nav class="navbar navbar-expand-md navbar-light bg-light rounded mb-3">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav text-md-center nav-justified w-100">
                    <li class="nav-item active">
                        <a class="nav-link" href="/home">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/browse">Browse</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/search">Search</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

    <div id="content">
        <h3>Welcome <?php if ($accountName) echo $accountName;?></h3>
        <hr>
        <h5>Usage Instructions:</h5>
        <p>
            Browse all products <a href="/browse">here</a>
            <br>
            or
            <br>
            Search for a specific product <a href="/search">here</a>
        </p>
    </div>
</div>
<?php
    include "footer.phtml"
?>
